### ISSUE TITLE
Support for Subdomains?

### ISSUE THREAD

**Issue by kevdel** [sdr-enthusiasts/docker-reversewebproxy#25]
is there a way in the config to include subdomain in the config?

 tar1090.domain.com|http://10.0.0.191/tar1090

**Comment by kx1t** [comment]
At this moment -- not yet. It currently applies the same rules for all of the domains and the entry in front of the `|` separator is interpreted to be the file or directory name of the HTTP `GET` request.

However, this is something that can be configured in `nginx`, which is the underlying web server engine for `reversewebproxy`. It would just add substantially to the complexity to implement this.

Of course, if you'd want to try to implement it yourself, feel free to fork / implement / submit a PR. [This is the specific file](https://github.com/sdr-enthusiasts/docker-reversewebproxy/blob/main/rootfs/etc/cont-init.d/20-webproxy) with the logic to turn the Docker Variables into a `nginx` setup - you'd have to add code (`bash` script) there.

**Comment by kx1t** [comment]
I am going to close this issue as I don't think that it will be implemented, unless someone wants to contribute a solution to the code.
