### ISSUE TITLE
export access_log to external 

### ISSUE THREAD

**Issue by NgTrThanh** [sdr-enthusiasts/docker-reversewebproxy#28]
Hello, 
Could you make access_log expose to external to NGINX Log Analyzer Tools.
I plan to use with this tool
GoAccess for Nginx Proxy Manager Logs
https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager

I would like to add following to /ect/nginx/nginx.conf

> access_log /config/log/default.log proxy;
> log_format standard '[$time_local] $status - $request_method $scheme $host "$request_uri" [Client $remote_addr] [Length $body_bytes_sent] [Gzip $gzip_ratio] "$http_user_agent" "$http_referer"';

Thank you.

**Comment by kx1t** [comment]
Hi,

- you can map a docker volume to `/var/log/nginx` to expose your logs to the host. This should allow your logs analyzer to access them
- Unfortunately, the BotBlock code depends on the current logging format. As such, it would be a lot of work to support a different log file format.

Based on this, I will close your Issue as a "deferred feature request".
