### ISSUE TITLE
ghcr.io access denied

### ISSUE THREAD

**Issue by om3wuc** [sdr-enthusiasts/docker-reversewebproxy#37]
Default yaml parsing ends with error:  could not find expected...
Why the docker login is needed? Is it not a privacy limitation?

**Comment by kx1t** [comment]
Must have been a temporary issue with ghcr.io. There is no privacy limitation and for several of my deployments (and those of others), docker pulls the image at `ghcr.io/sdr-enthusiasts/docker-reversewebproxy:latest` without any problems.

If you come across this again, please feel free to re-open the issue or file a new one.
(Also, sorry for the delay in addressing this)
